import { Sequelize } from 'sequelize-typescript';
import TestEntityModel from './fixtures/test-entity.model';
import { ConflictException, Logger, NotFoundException } from '@nestjs/common';
import TestRepository from './fixtures/test.repository';
import { randomUUID } from 'node:crypto';
import RepositoryOptionsInterface from '@database/interfaces/repository-options.interface';
import AbstractRepository from '@database/repositories/abstract.repository';
import PaginationDto from '@common/dto/pagination.dto';
import DataRangeEnum from '@common/enums/data-range.enum';

const length = 10000;
const logger = new Logger('Test logger');
const opts: RepositoryOptionsInterface<TestEntityModel> = {
  logger,
  createMessage: 'No se pudo crear el registro',
  insertManyMessage: 'No se pudieron crear los registros',
  findOrCreateMessage: 'No se pudo buscar o crear el registro',
  findByPkMessage: 'No se pudo buscar el registro',
  findByPkNotFoundMessage: 'Registro no encontrado',
  findOneMessage: 'No se pudo buscar el registro',
  findOneNotFoundMessage: 'Registro no encontrado',
  findAllMessage: 'No se pudieron listar los registros',
  findAllPaginatedMessage: 'No se pudieron listar los registros',
  updateByPkMessage: 'No se pudo actualizar el registro',
  updateByQueryMessage: 'No se pudo actualizar el registro',
  deleteByPkMessage: 'No se pudo eliminar el registro',
  restoreByPkMessage: 'No se pudo restaurar el registro',
  transactionMessage: 'No se pudo completar la transacción',
};

let repository: TestRepository;

describe('AbstractRepository', () => {
  let sequelize: Sequelize;

  beforeEach(async () => {
    sequelize = new Sequelize({
      dialect: 'sqlite',
      storage: ':memory:',
      logging: false,
      models: [TestEntityModel],
    });

    repository = new TestRepository(TestEntityModel, opts);
    repository.unassignLoggerError();

    await sequelize.sync({ force: true });
  });

  afterEach(async () => {
    await sequelize.close();
  });

  describe('Constructor - Incorrect Instance', () => {
    it('should be throw exception to directly instance', () => {
      expect(() => new AbstractRepository(TestEntityModel, {})).toThrow(
        ConflictException,
      );
    });
  });

  describe('Constructor - Instance', () => {
    it('should be not throw exception to instance', () => {
      repository = new TestRepository(TestEntityModel, opts);
      expect(repository).toBeDefined();
    });
  });

  describe('Id Object', () => {
    it('should be generated by custom function', async () => {
      repository = new TestRepository(TestEntityModel, {
        ...opts,
        idGenerator: randomUUID,
      });

      await repository.create({});
    });

    it('should be generated by custom function', async () => {
      repository = new TestRepository(TestEntityModel, opts);

      await repository.create({});
    });
  });

  describe('Create Method', () => {
    it('should be correct', async () => {
      const entity = await repository.create({});

      expect(entity).toBeDefined();
      expect(entity.id).toBeDefined();
      expect(entity).toHaveProperty('id');
    });

    describe('Ids uniques', () => {
      it('should be generated by custom function', async () => {
        const fn = () => 'notUniqueId';

        repository = new TestRepository(TestEntityModel, {
          ...opts,
          idGenerator: fn,
        });

        const original = await repository.create({ id: fn() });
        expect(original).toBeDefined();
        expect(original).toHaveProperty('id');

        const duplicated = repository.create({ id: fn() });

        await expect(duplicated).rejects.toThrow();
        await expect(duplicated).rejects.toThrow(ConflictException);
        await expect(duplicated).rejects.toThrow(opts.createMessage);
      });
    });
  });

  describe('Insert Many Method', () => {
    it('should be correct', async () => {
      repository = new TestRepository(TestEntityModel, {
        ...opts,
        idGenerator: randomUUID,
      });

      const entities = [];
      for (let i = 0; i < length; i++) {
        entities.push({ name: `name-${i}` });
      }

      const entity = await repository.insertMany(entities);

      expect(entity).toBeDefined();
      expect(entity).toHaveLength(length);
      expect(entity).toHaveProperty('length');

      const entitiesFound = await repository.findAll();
      expect(entitiesFound).toHaveLength(length);
    });

    it('Ids duplicates', async () => {
      repository = new TestRepository(TestEntityModel, {
        ...opts,
        idGenerator: () => 'notUniqueId',
      });

      const entities = [];
      for (let i = 0; i < length; i++) {
        entities.push({ name: `name-${i}` });
      }

      const res = repository.insertMany(entities);

      await expect(res).rejects.toThrow();
      await expect(res).rejects.toThrow(ConflictException);
      await expect(res).rejects.toThrow(opts.insertManyMessage);
    });
  });

  describe('Find or Create Method', () => {
    it('should be correct', async () => {
      const id = 'id';

      const [, first] = await repository.findOrCreate({
        where: { id },
        defaults: { id, name: randomUUID() },
      });

      const [, second] = await repository.findOrCreate({
        where: { id },
        defaults: { id, name: randomUUID() },
      });

      const [, third] = await repository.findOrCreate({
        where: { id: id.concat(id) },
      });

      expect(first).toBeTruthy();
      expect(second).toBeFalsy();
      expect(third).toBeTruthy();
    });

    it('Wrong Data', async () => {
      const res = repository.findOrCreate({});

      await expect(res).rejects.toThrow();
      await expect(res).rejects.toThrow(ConflictException);
      await expect(res).rejects.toThrow(opts.findOrCreateMessage);
    });
  });

  describe('find by PK Method', () => {
    it('should be correct', async () => {
      const id = randomUUID();
      const name = randomUUID().concat('-name');

      await repository.create({ id, name });

      const found = (await repository.findByPk(id, false)) as TestEntityModel;

      expect(found).toBeDefined();
      expect(found).toHaveProperty('id');
      expect(found).toHaveProperty('name');
      expect(found.name).toEqual(name);
      expect(found.id).not.toEqual(name);
    });

    it('should be not found', async () => {
      const id = randomUUID();

      await repository.create({ id });

      const found = repository.findByPk('id', true);

      await expect(found).rejects.toThrow();
      await expect(found).rejects.toThrow(NotFoundException);
      await expect(found).rejects.toThrow(opts.findByPkNotFoundMessage);
    });

    it('should be throw exception', async () => {
      const id = [undefined] as unknown as string;

      await repository.create({ id });

      const found = repository.findByPk(id, true);

      await expect(found).rejects.toThrow();
      await expect(found).rejects.toThrow(ConflictException);
      await expect(found).rejects.toThrow(opts.findByPkMessage);
    });
  });

  describe('find One Method', () => {
    it('should be correct', async () => {
      const name = 'Carlos';

      await repository.create({ id: randomUUID(), name });

      const found = (await repository.findOne(
        { name },
        false,
      )) as TestEntityModel;

      expect(found).toBeDefined();
      expect(found).toHaveProperty('id');
      expect(found).toHaveProperty('name');
      expect(found.name).toEqual(name);
    });

    it('should be not found', async () => {
      const name = 'Ernesto';

      await repository.create({ id: randomUUID(), name });

      const found = repository.findOne({ id: name }, true);

      await expect(found).rejects.toThrow();
      await expect(found).rejects.toThrow(NotFoundException);
      await expect(found).rejects.toThrow(opts.findOneNotFoundMessage);
    });

    it('should be throw exception', async () => {
      const id = [undefined] as unknown as string;

      const found = repository.findOne({ id, name: id }, false, {
        attributes: ['xxx'],
      });

      await expect(found).rejects.toThrow();
      await expect(found).rejects.toThrow(ConflictException);
      await expect(found).rejects.toThrow(opts.findOneMessage);
    });
  });

  describe('find All Method', () => {
    it('should be correct', async () => {
      const entities = [];
      for (let i = 0; i < length; i++) {
        entities.push({ name: `name-${i}` });
      }

      await repository.insertMany(entities);

      const list = await repository.findAll();

      expect(list).toBeDefined();
      expect(list).toHaveProperty('length');
    });

    it('should be exception', async () => {
      const list = repository.findAll({ attribute: ['xxx'] });

      await expect(list).rejects.toThrow();
      await expect(list).rejects.toThrow(ConflictException);
      await expect(list).rejects.toThrow(opts.findAllMessage);
    });
  });

  describe('find All Paginated Method', () => {
    it('should be correct', async () => {
      const entities = [];
      for (let i = 0; i < length; i++) {
        entities.push({ name: `name-${i}` });
      }
      const dto = new PaginationDto();
      dto.page = 1;
      dto.pageSize = 10;
      dto.orderBy = 'createdAt';
      dto.range = DataRangeEnum.THIS_MONTH;

      await repository.insertMany(entities);

      const list = await repository.findAllPaginated(dto);

      expect(list).toBeDefined();
      expect(list.meta.page).toEqual(dto.page);
      expect(list.meta.pageSize).toEqual(dto.pageSize);

      dto.pageSize = 100;
      dto.page = 1000000;

      await repository.findAllPaginated(dto);
    });

    it('should be exception', async () => {
      const dto = new PaginationDto();

      const list = repository.findAllPaginated(
        dto,
        {},
        { attributes: ['xxx'] },
      );

      await expect(list).rejects.toThrow();
      await expect(list).rejects.toThrow(ConflictException);
      await expect(list).rejects.toThrow(opts.findAllMessage);
    });
  });

  describe('Update by PK Method', () => {
    it('should be correct', async () => {
      const id = randomUUID();
      const name = 'Carlos';
      const newName = 'Ernesto';

      await repository.create({ id, name });

      const entity = (await repository.findByPk(id, true)) as TestEntityModel;

      await repository.updateByPk(id, { name: newName });
      let entityUpdated = (await repository.findByPk(
        id,
        true,
      )) as TestEntityModel;

      expect(entity.id).toEqual(id);
      expect(entityUpdated.id).toEqual(id);
      expect(entityUpdated.name).toEqual(newName);
      expect(entity.name).not.toEqual(newName);

      await repository.updateByPk(id, { name });
      entityUpdated = (await repository.findByPk(id, true)) as TestEntityModel;

      expect(entity.id).toEqual(entityUpdated.id);
      expect(entity.name).toEqual(name);
      expect(entityUpdated.name).toEqual(name);

      await repository.updateByPk(id.concat('-id'), { name: newName });
      entityUpdated = (await repository.findByPk(id, true)) as TestEntityModel;
      expect(entityUpdated.name).toEqual(name);
    });

    it('should be exception', async () => {
      const id = randomUUID();
      const name = 'Carlos';
      await repository.create({ id, name });

      const promise = repository.updateByPk(
        id,
        { name: id.concat('-').concat(name) },
        { fields: true as unknown as string[] },
      );

      await expect(promise).rejects.toThrow();
      await expect(promise).rejects.toThrow(ConflictException);
      await expect(promise).rejects.toThrow(opts.updateByQueryMessage);
    });
  });

  describe('Update by Query Method', () => {
    it('should be correct', async () => {
      const id = randomUUID();
      const name = 'Carlos';
      const newName = 'Ernesto';

      await repository.create({ id, name });

      const entityUpdated = await repository.updateByQuery(
        { id },
        { name: newName },
      );

      expect(entityUpdated).toBeDefined();
      expect(entityUpdated!.id).toEqual(id);
      expect(entityUpdated!.name).toEqual(newName);

      const found = (await repository.findByPk(id, true)) as TestEntityModel;
      expect(found.name).toEqual(newName);
    });

    it('should be not found', async () => {
      const id = randomUUID();
      const name = 'Carlos';

      await repository.create({ id, name });

      const promise = repository.updateByQuery(
        { id: id.concat('-id') },
        { name: 'Ernesto' },
      );

      await expect(promise).rejects.toThrow();
      await expect(promise).rejects.toThrow(NotFoundException);
      await expect(promise).rejects.toThrow(opts.findOneNotFoundMessage);
    });

    it('should be exception', async () => {
      const id = randomUUID();
      const name = 'Carlos';

      await repository.create({ id, name });

      const promise = repository.updateByQuery(
        { id },
        { name: id.concat('-').concat(name) },
        { fields: true as unknown as string[] },
      );

      await expect(promise).rejects.toThrow();
      await expect(promise).rejects.toThrow(ConflictException);
      await expect(promise).rejects.toThrow(opts.updateByQueryMessage);
    });
  });

  describe('Delete by PK Method', () => {
    it('should be correct', async () => {
      const id = randomUUID();

      await repository.create({ id });

      let entity = (await repository.findByPk(id, true)) as TestEntityModel;

      expect(entity).toBeDefined();
      expect(entity.id).toEqual(id);

      await repository.deleteByPk(id);
      await repository.deleteByPk(id);
    });

    it('should be exception', async () => {
      const id = randomUUID();

      await repository.create({ id });

      const promise = repository.deleteByPk(id, {
        transaction: true as unknown as any,
      });

      await expect(promise).rejects.toThrow();
      await expect(promise).rejects.toThrow(ConflictException);
      await expect(promise).rejects.toThrow(opts.deleteByPkMessage);
    });
  });

  describe('Restore by PK Method', () => {
    it('should be correct', async () => {
      const id = randomUUID();

      await repository.create({ id });
      await repository.deleteByPk(id);

      const restored = await repository.restoreByPk(id);
      const found = (await repository.findByPk(id, true)) as TestEntityModel;

      expect(restored).toBeDefined();
      expect(restored!.id).toEqual(id);
      expect(found).toBeDefined();
      expect(found.id).toEqual(id);

      const notFound = await repository.restoreByPk(id.concat('-id'));
      expect(notFound).toBeNull();
    });

    it('should be exception', async () => {
      const id = randomUUID();

      await repository.create({ id });
      await repository.deleteByPk(id);

      const promise = repository.restoreByPk(id, {
        transaction: true as unknown as any,
      });

      await expect(promise).rejects.toThrow();
      await expect(promise).rejects.toThrow(ConflictException);
      await expect(promise).rejects.toThrow(opts.restoreByPkMessage);
    });
  });

  describe('Transaction Method', () => {
    it('should be correct', async () => {
      const id = randomUUID();

      const result = await repository.transaction(async (transaction) => {
        return repository.create({ id }, { transaction });
      });

      expect(result).toBeDefined();
      expect(result.id).toEqual(id);

      const found = (await repository.findByPk(id, true)) as TestEntityModel;
      expect(found.id).toEqual(id);
    });

    it('should be exception', async () => {
      const promise = repository.transaction(async () => {
        throw new Error('Error dentro de la transacción');
      });

      await expect(promise).rejects.toThrow();
      await expect(promise).rejects.toThrow(ConflictException);
      await expect(promise).rejects.toThrow(opts.transactionMessage);
    });
  });

  // ---------------------------------------------------------------------------
  // Real test
  // ---------------------------------------------------------------------------

  describe('Real World Edge Cases', () => {
    describe('Soft Delete Visibility (paranoid)', () => {
      it('findAll should not return soft-deleted rows by default', async () => {
        const idA = randomUUID();
        const idB = randomUUID();

        await repository.create({ id: idA });
        await repository.create({ id: idB });
        await repository.deleteByPk(idA);

        const list = await repository.findAll();

        expect(list).toHaveLength(1);
        expect(list[0].id).toEqual(idB);
      });

      it('findAllPaginated total should exclude soft-deleted rows', async () => {
        const idA = randomUUID();
        const idB = randomUUID();

        await repository.create({ id: idA });
        await repository.create({ id: idB });
        await repository.deleteByPk(idA);

        const dto = new PaginationDto();
        dto.page = 1;
        dto.pageSize = 10;

        const list = await repository.findAllPaginated(dto);

        expect(list.meta.total).toEqual(1);
        expect(list.data).toHaveLength(1);
        expect(list.data[0].id).toEqual(idB);
      });

      it('findOne(query, true) should not find a soft-deleted row and throws NotFoundException', async () => {
        const id = randomUUID();
        const name = 'soft-deleted-name';

        await repository.create({ id, name });
        await repository.deleteByPk(id);

        const found = repository.findOne({ name }, true);

        await expect(found).rejects.toThrow(NotFoundException);
        await expect(found).rejects.toThrow(opts.findOneNotFoundMessage);
      });

      it('updateByPk on a soft-deleted row should be a no-op (returns null, data unchanged)', async () => {
        const id = randomUUID();
        const name = 'original';

        await repository.create({ id, name });
        await repository.deleteByPk(id);

        const result = await repository.updateByPk(id, { name: 'changed' });
        expect(result).toBeNull();

        const restored = await repository.restoreByPk(id);
        expect(restored!.name).toEqual(name);
      });

      it('updateByQuery on a soft-deleted row should throw NotFoundException, not update it', async () => {
        const id = randomUUID();
        const name = 'original';

        await repository.create({ id, name });
        await repository.deleteByPk(id);

        const promise = repository.updateByQuery({ id }, { name: 'changed' });

        await expect(promise).rejects.toThrow(NotFoundException);
        await expect(promise).rejects.toThrow(opts.findOneNotFoundMessage);

        const restored = await repository.restoreByPk(id);
        expect(restored!.name).toEqual(name);
      });

      it('paranoid: false should still find a soft-deleted row', async () => {
        const id = randomUUID();

        await repository.create({ id });
        await repository.deleteByPk(id);

        const found = (await repository.findByPk(id, true, {
          paranoid: false,
        })) as TestEntityModel;

        expect(found).toBeDefined();
        expect(found.id).toEqual(id);
        expect(found.deletedAt).not.toBeNull();
      });
    });

    describe('Hard Delete (force) is unrecoverable', () => {
      it('force delete should make the row permanently disappear, even with paranoid: false', async () => {
        const id = randomUUID();

        await repository.create({ id });
        await repository.deleteByPk(id, { force: true });

        const found = repository.findByPk(id, true, { paranoid: false });
        await expect(found).rejects.toThrow(NotFoundException);

        const restored = await repository.restoreByPk(id);
        expect(restored).toBeNull();
      });
    });

    describe('updateByQuery ambiguity with multiple matches', () => {
      it('should only update the first matching row, leaving the rest untouched', async () => {
        const sharedName = 'duplicate-name';

        await repository.create({ id: randomUUID(), name: sharedName });
        await repository.create({ id: randomUUID(), name: sharedName });
        await repository.create({ id: randomUUID(), name: sharedName });

        await repository.updateByQuery(
          { name: sharedName },
          { name: 'updated-name' },
        );

        const stillOld = await repository.findAll({ name: sharedName });
        const updated = await repository.findAll({ name: 'updated-name' });

        expect(stillOld).toHaveLength(2);
        expect(updated).toHaveLength(1);
      });
    });

    describe('Transaction Atomicity', () => {
      it('should roll back every operation performed inside a failed transaction', async () => {
        const idA = randomUUID();
        const idB = randomUUID();

        const promise = repository.transaction(async (transaction) => {
          await repository.create({ id: idA }, { transaction });
          await repository.create({ id: idB }, { transaction });
          throw new Error('simulated failure mid-transaction');
        });

        await expect(promise).rejects.toThrow(ConflictException);

        const all = await repository.findAll();
        expect(all).toHaveLength(0);
      });

      it('should commit every operation when the transaction succeeds', async () => {
        const idA = randomUUID();
        const idB = randomUUID();

        await repository.transaction(async (transaction) => {
          await repository.create({ id: idA, name: 'a' }, { transaction });
          await repository.updateByPk(
            idA,
            { name: 'a-updated' },
            { transaction },
          );
          await repository.create({ id: idB, name: 'b' }, { transaction });
        });

        const all = await repository.findAll();
        expect(all).toHaveLength(2);

        const found = (await repository.findByPk(idA, true)) as TestEntityModel;
        expect(found.name).toEqual('a-updated');
      });
    });

    describe('Pagination Edge Cases', () => {
      const total = 5;

      beforeEach(async () => {
        const entities = [];
        for (let i = 0; i < total; i++) {
          entities.push({ name: `name-${i}` });
        }
        await repository.insertMany(entities);
      });

      it('a page beyond the last one returns empty data with consistent meta', async () => {
        const dto = new PaginationDto();
        dto.page = 999;
        dto.pageSize = 10;

        const list = await repository.findAllPaginated(dto);

        expect(list.data).toHaveLength(0);
        expect(list.meta.total).toEqual(total);
        expect(list.meta.hasNext).toBe(false);
        expect(list.meta.hasPrev).toBe(true);
        expect(list.meta.nextPage).toBeNull();
        expect(list.meta.prevPage).toEqual(998);
      });

      it('pageSize 0 yields no rows and a non-finite totalPages (known quirk)', async () => {
        const dto = new PaginationDto();
        dto.page = 1;
        dto.pageSize = 0;

        const list = await repository.findAllPaginated(dto);

        expect(list.data).toHaveLength(0);
        expect(list.meta.total).toEqual(total);
        expect(list.meta.totalPages).toBe(Infinity);
      });

      it('a negative page produces a negative offset that sqlite ignores, returning all rows (known quirk)', async () => {
        const dto = new PaginationDto();
        dto.page = -1;
        dto.pageSize = 10;

        const list = await repository.findAllPaginated(dto);

        expect(list.data).toHaveLength(total);
        expect(list.meta.from).toEqual(-19);
        expect(list.meta.to).toEqual(-10);
      });
    });

    describe('Malicious & Extreme Input', () => {
      it('should safely store and retrieve a SQL-injection-like string without affecting the table', async () => {
        const id = randomUUID();
        const maliciousName = "Robert'); DROP TABLE test_entities;--";

        await repository.create({ id, name: maliciousName });

        const found = (await repository.findByPk(id, true)) as TestEntityModel;
        expect(found.name).toEqual(maliciousName);

        const all = await repository.findAll();
        expect(all).toHaveLength(1);
      });

      it('should round-trip a very long string', async () => {
        const id = randomUUID();
        const longName = 'x'.repeat(100000);

        await repository.create({ id, name: longName });

        const found = (await repository.findByPk(id, true)) as TestEntityModel;
        expect(found.name).toHaveLength(100000);
        expect(found.name).toEqual(longName);
      });

      it('should round-trip unicode and emoji characters', async () => {
        const id = randomUUID();
        const unicodeName = '日本語 🎉 Ñoño café';

        await repository.create({ id, name: unicodeName });

        const found = (await repository.findByPk(id, true)) as TestEntityModel;
        expect(found.name).toEqual(unicodeName);
      });
    });

    describe('Concurrency & Race Conditions', () => {
      it('parallel creates with a real id generator should never collide', async () => {
        repository = new TestRepository(TestEntityModel, {
          ...opts,
          idGenerator: randomUUID,
        });

        const creations = Array.from({ length: 100 }, (_, i) =>
          repository.create({ name: `parallel-${i}` }),
        );

        const results = await Promise.all(creations);
        const ids = new Set(results.map((entity) => entity.id));

        expect(ids.size).toEqual(100);
      });

      it('two concurrent updateByPk calls on the same row should not corrupt data', async () => {
        const id = randomUUID();
        await repository.create({ id, name: 'start' });

        await Promise.all([
          repository.updateByPk(id, { name: 'A' }),
          repository.updateByPk(id, { name: 'B' }),
        ]);

        const found = (await repository.findByPk(id, true)) as TestEntityModel;
        expect(['A', 'B']).toContain(found.name);
      });

      it('back-to-back transactions should each commit independently', async () => {
        // sqlite in-memory forces a single connection, so true parallel
        // transactions aren't representative here; run sequentially and
        // still verify each one commits its own work correctly.
        const ids = Array.from({ length: 10 }, () => randomUUID());

        for (const id of ids) {
          await repository.transaction((transaction) =>
            repository.create({ id }, { transaction }),
          );
        }

        const all = await repository.findAll();
        expect(all).toHaveLength(10);
      });
    });

    describe('findByPk/findOne with validate=false on a missing row', () => {
      it('findByPk(id, false) returns null instead of throwing', async () => {
        const found = await repository.findByPk(randomUUID(), false);

        expect(found).toBeNull();
      });

      it('findOne(query, false) returns null instead of throwing', async () => {
        const found = await repository.findOne({ name: randomUUID() }, false);

        expect(found).toBeNull();
      });
    });
  });
});
