import { sql } from 'drizzle-orm';
import { timestamp, uuid } from 'drizzle-orm/pg-core';

// Reusable base columns: every table extends this the same way BaseModel
// used to. Gives id (UUID v7, generated by Postgres), createdAt, updatedAt
// and soft delete (deletedAt) for free.
export const baseColumns = {
  id: uuid('id')
    .primaryKey()
    .default(sql`uuidv7()`),

  createdAt: timestamp('created_at', { withTimezone: true })
    .notNull()
    .defaultNow(),

  updatedAt: timestamp('updated_at', { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),

  deletedAt: timestamp('deleted_at', { withTimezone: true }),
};
